### ISSUE TITLE
Critical Theory

### ISSUE THREAD

**Issue by debatik** [Debatikcenter/debatikcenter#11]
8. Re: "Critical Theory" - The text "These are (not) the things..." needs to be justified. Additionally, the endnotes need to be added.

**Comment by ArmandoLulaj** [comment]
The text is justified. GREAT! But the endnotes are still missing. Please use the file attached here.

**Comment by ArmandoLulaj** [comment]
.

**Comment by ArmandoLulaj** [comment]
.

**Comment by ArmandoLulaj** [comment]
I can't seem to be able to attach the text here so I'm sending it via gmail. Sorry.

**Comment by ArmandoLulaj** [comment]
Just sent it. Please use the text as is, without making any changes. 
(In the current version there are all kinds of problems - like the fact that the titles of artworks, books, etc., do not appear in italics as they should.)

**Comment by sidorelauku** [comment]
Critical theory is updated. The endnotes are added. But still a bit work with design. 
Do you think we need a line like I did there or not before endnotes?
Also in italic are all the words as on the document you sent me.

**Comment by JonidaG** [comment]
Thank you for adding the endnotes! There are still a few issues, however, namely:

- I noticed that the links in the endnotes did not work, meaning you could not simply click on them in order to access the pages they link to. I realised this was my fault, since when including these links in my document I had used copy/paste instead of adding them as hyperlinks. I have now rectified this issue and am attaching the text here once more with hyperlinks.
- Regarding the endnotes, in the main body of the text the numbers appear against a grey background which they shouldn't. The background should be white.
- Also regarding the endnotes, in the actual endnote section at the end of the text, the numbers on the left hand side appear to be the same size and on the same level as the text adjacent to them. Instead, they should be smaller in size and slightly higher than the text adjacent to them. Please refer to the document attached here to get an idea of how they should look.
- Finally, unlike the main body of the text which is justified, the endnotes should be aligned on the left. I know this seems strange but it is standard academic procedure.

[These are (not) the things we are fighting for!.docx](https://github.com/Debatikcenter/debatikcenter/files/1813211/These.are.not.the.things.we.are.fighting.for.docx)

**Comment by sidorelauku** [comment]
Updated. Also added footer at the end.

**Comment by JonidaG** [comment]
Thank you so much for making the changes! The numbers in the main body of the text are absolutely fine! There are still a couple of small things though, namely:

1. In the endnote section, the numbers should be the same size as in the main text, so 7pt. Additionally, they should be positioned slightly above the adjacent texts.
2. Also in the endnote section, if you look at endnote no. 9, the link is missing. The full endnote is as follows:  "See, for example, the website of the National Territorial Planning Agency:  <http://www.planifikimi.gov.al/>"

**Comment by sidorelauku** [comment]
@JonidaG  updated font-size for numbers on endnotes to 7pt & adding the link to no.9.

**Comment by JonidaG** [comment]
That's brilliant @sidorelauku! 

One last thing regarding the positioning of the numbers in the endnote section. If you take as reference the height of the text adjacent to each number, the number should be placed in the upper half as opposed to the lower half of the text.

**Comment by sidorelauku** [comment]
Hey @JonidaG the numbers on endnotes are now placed on upper half. Is it ok?

**Comment by JonidaG** [comment]
It's looking great @sidorelauku!
